const INVALID_TOKEN = 'INVALID_TOKEN';

const RESPONSE_STATUS = {
  SUCESS: 200,
  NOT_FOUND: 404,
  INTERVAL_SERVER: 500,
  FORBIDDEN: 403,
};

const ACCESS_TOKEN = '@@token';

export default {
  INVALID_TOKEN,
  RESPONSE_STATUS,
  ACCESS_TOKEN,
};
